-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 09:48:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema green_go
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema green_go
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `green_go` DEFAULT CHARACTER SET utf8 ;
USE `green_go` ;

-- -----------------------------------------------------
-- Table `green_go`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`especie` (
  `idEspecie` INT NOT NULL,
  `nomePop` VARCHAR(100) NOT NULL,
  `nomeCie` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  `frutifera` TINYINT(1) NOT NULL,
  `comestivel` TINYINT(1) NOT NULL,
  `raridade` TINYINT(1) NOT NULL,
  `medicinal` TINYINT(1) NOT NULL,
  `toxidade` TINYINT(1) NOT NULL,
  `exotica` TINYINT(1) NOT NULL,
  UNIQUE INDEX `idEspecie_UNIQUE` (`idEspecie` ASC) VISIBLE,
  PRIMARY KEY (`idEspecie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `green_go`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`zona` (
  `idZona` INT NOT NULL,
  `qntPlantas` INT NOT NULL,
  `pontoZona` INT NOT NULL,
  `nomeZona` VARCHAR(100) NOT NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idZona`),
  UNIQUE INDEX `idZona_UNIQUE` (`idZona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`usuario` (
  `idUsuario` INT NOT NULL,
  `nomeUsuario` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(40) NOT NULL,
  `escolaridade` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipoUsuario` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`equipe` (
  `idEquipe` INT NOT NULL,
  `nomeEquipe` VARCHAR(100) NOT NULL,
  `codEntrada` INT NOT NULL,
  `cor` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `idEquipe_UNIQUE` (`idEquipe` ASC) VISIBLE,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`planta` (
  `idPlanta` INT NOT NULL,
  `idZona` INT NOT NULL,
  `idEspecie` INT NOT NULL,
  `codNumerico` INT NOT NULL,
  `codQR` VARCHAR(5000) NOT NULL,
  `nomeSocial` VARCHAR(45) NOT NULL,
  `historia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlanta`),
  UNIQUE INDEX `idPlanta_UNIQUE` (`idPlanta` ASC) VISIBLE,
  INDEX `fk_planta_1_idx` (`idZona` ASC) VISIBLE,
  INDEX `fk_planta_2_idx` (`idEspecie` ASC) VISIBLE,
  UNIQUE INDEX `idZona_UNIQUE` (`idZona` ASC) VISIBLE,
  UNIQUE INDEX `idEspecie_UNIQUE` (`idEspecie` ASC) VISIBLE,
  CONSTRAINT `fk_planta_1`
    FOREIGN KEY (`idZona`)
    REFERENCES `green_go`.`zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planta_2`
    FOREIGN KEY (`idEspecie`)
    REFERENCES `green_go`.`especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`equipe_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`equipe_usuario` (
  `idEquipeUsuario` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idEquipeUsuario`),
  INDEX `fk_myuser_has_equipe_equipe1_idx` (`idEquipe` ASC) VISIBLE,
  INDEX `fk_myuser_has_equipe_myuser1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_myuser_has_equipe_myuser1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `green_go`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_myuser_has_equipe_equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `green_go`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`quiz` (
  `idQuiz` INT NOT NULL,
  `maximoPergunta` INT NOT NULL,
  `nomeQuiz` VARCHAR(45) NOT NULL,
  `comTempo` TINYINT NOT NULL,
  `quantTempo` INT NOT NULL,
  `zona_idZona` INT NOT NULL,
  PRIMARY KEY (`idQuiz`),
  INDEX `fk_quiz_zona1_idx` (`zona_idZona` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_zona1`
    FOREIGN KEY (`zona_idZona`)
    REFERENCES `green_go`.`zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida` (
  `idPartida` INT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idPartida`),
  INDEX `fk_partida_quiz1_idx` (`idQuiz` ASC) VISIBLE,
  UNIQUE INDEX `idPartida_UNIQUE` (`idPartida` ASC) VISIBLE,
  CONSTRAINT `fk_partida_quiz1`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `green_go`.`quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`questao` (
  `idQuestao` INT NOT NULL,
  `descricaoQ` VARCHAR(200) NOT NULL,
  `grauDifilculdade` ENUM("facil", "medio", "dificil") NOT NULL,
  `pontuacao` INT NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`idQuestao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`questao_especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`questao_especie` (
  `idQuestaoEspecie` INT NOT NULL AUTO_INCREMENT,
  `idEspecie` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  INDEX `fk_especie_has_pergunta_pergunta1_idx` (`idQuestao` ASC) VISIBLE,
  INDEX `fk_especie_has_pergunta_especie1_idx` (`idEspecie` ASC) VISIBLE,
  PRIMARY KEY (`idQuestaoEspecie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `green_go`.`resp_usua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`resp_usua` (
  `idRespUsua` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  `acertou` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idRespUsua`),
  INDEX `fk_resp_usua_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_resp_usua_questao1_idx` (`idQuestao` ASC) VISIBLE,
  CONSTRAINT `fk_resp_usua_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `green_go`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resp_usua_questao1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `green_go`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida_zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida_zona` (
  `idPartidaZona` INT NOT NULL,
  `idZona` INT NOT NULL,
  `idPartida` INT NOT NULL,
  PRIMARY KEY (`idPartidaZona`),
  INDEX `fk_zona_has_partida_partida1_idx` (`idPartida` ASC) VISIBLE,
  INDEX `fk_zona_has_partida_zona1_idx` (`idZona` ASC) VISIBLE,
  UNIQUE INDEX `idZonaPartida_UNIQUE` (`idPartidaZona` ASC) VISIBLE,
  CONSTRAINT `fk_zona_has_partida_zona1`
    FOREIGN KEY (`idZona`)
    REFERENCES `green_go`.`zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_has_partida_partida1`
    FOREIGN KEY (`idPartida`)
    REFERENCES `green_go`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida_equipe` (
  `idPartidaEquipe` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  `idPartida` INT NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`idPartidaEquipe`),
  INDEX `fk_equipe_has_partida_partida1_idx` (`idPartida` ASC) VISIBLE,
  INDEX `fk_equipe_has_partida_equipe1_idx` (`idEquipe` ASC) VISIBLE,
  UNIQUE INDEX `idEquipePartida_UNIQUE` (`idPartidaEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_partida_equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `green_go`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_partida_partida1`
    FOREIGN KEY (`idPartida`)
    REFERENCES `green_go`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`alternativa` (
  `idAlternativa` INT NOT NULL AUTO_INCREMENT,
  `descricaoAlternativa` VARCHAR(200) NOT NULL,
  `alternativaCerta` TINYINT NOT NULL,
  `idQuestao` INT NOT NULL,
  `resp_usua_idRespUsua` INT NOT NULL,
  INDEX `fk_alternativa_questao1_idx` (`idQuestao` ASC) VISIBLE,
  PRIMARY KEY (`idAlternativa`),
  INDEX `fk_alternativa_resp_usua1_idx` (`resp_usua_idRespUsua` ASC) VISIBLE,
  CONSTRAINT `fk_alternativa_questao1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `green_go`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alternativa_resp_usua1`
    FOREIGN KEY (`resp_usua_idRespUsua`)
    REFERENCES `green_go`.`resp_usua` (`idRespUsua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`quiz_has_questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`quiz_has_questao` (
  `quiz_idQuiz` INT NOT NULL,
  `questao_idQuestao` INT NOT NULL,
  PRIMARY KEY (`quiz_idQuiz`, `questao_idQuestao`),
  INDEX `fk_quiz_has_questao_questao1_idx` (`questao_idQuestao` ASC) VISIBLE,
  INDEX `fk_quiz_has_questao_quiz1_idx` (`quiz_idQuiz` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_has_questao_quiz1`
    FOREIGN KEY (`quiz_idQuiz`)
    REFERENCES `green_go`.`quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_has_questao_questao1`
    FOREIGN KEY (`questao_idQuestao`)
    REFERENCES `green_go`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
