-- MySQL Script generated by MySQL Workbench
-- Mon May  8 16:25:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema green_go
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema green_go
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `green_go` DEFAULT CHARACTER SET utf8 ;
USE `green_go` ;

-- -----------------------------------------------------
-- Table `green_go`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`especie` (
  `idEspecie` INT NOT NULL AUTO_INCREMENT,
  `nomePop` VARCHAR(100) NOT NULL,
  `nomeCie` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  `frutifera` TINYINT(1) NOT NULL,
  `comestivel` TINYINT(1) NOT NULL,
  `raridade` TINYINT(1) NOT NULL,
  `medicinal` TINYINT(1) NOT NULL,
  `toxidade` TINYINT(1) NOT NULL,
  `exotica` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idEspecie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `green_go`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`questao` (
  `idQuestao` INT NOT NULL AUTO_INCREMENT,
  `descricaoQ` VARCHAR(200) NOT NULL,
  `grauDificuldade` ENUM("facil", "medio", "dificil") NOT NULL,
  `pontuacao` INT NOT NULL,
  `imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`idQuestao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  `maximoPergunta` INT NOT NULL,
  `nomeQuiz` VARCHAR(45) NOT NULL,
  `comTempo` TINYINT NOT NULL,
  `quantTempo` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  PRIMARY KEY (`idQuiz`),
  CONSTRAINT `fk_quiz_pergunta1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `green_go`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`zona` (
  `idZona` INT NOT NULL AUTO_INCREMENT,
  `qntPlantas` INT NOT NULL,
  `pontoZona` INT NOT NULL,
  `nomeZona` VARCHAR(100) NOT NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idZona`),
  CONSTRAINT `fk_zona_quiz1`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `green_go`.`quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(40) NOT NULL,
  `escolaridade` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipoUsuario` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `nomeEquipe` VARCHAR(100) NOT NULL,
  `codEntrada` INT NOT NULL,
  `cor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`planta` (
  `idPlanta` INT NOT NULL AUTO_INCREMENT,
  `idZona` INT NOT NULL,
  `idEspecie` INT NOT NULL,
  `codNumerico` INT NOT NULL,
  `codQR` VARCHAR(5000) NOT NULL,
  `nomeSocial` VARCHAR(45) NOT NULL,
  `historia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlanta`),
  CONSTRAINT `fk_planta_1`
    FOREIGN KEY (`idZona`)
    REFERENCES `green_go`.`zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planta_2`
    FOREIGN KEY (`idEspecie`)
    REFERENCES `green_go`.`especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`equipe_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`equipe_usuario` (
  `idEquipeUsuario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idEquipeUsuario`),
  CONSTRAINT `fk_myuser_has_equipe_myuser1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `green_go`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_myuser_has_equipe_equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `green_go`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida` (
  `idPartida` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idPartida`),
  CONSTRAINT `fk_partida_quiz1`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `green_go`.`quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`resposta` (
  `idResposta` INT NOT NULL AUTO_INCREMENT,
  `respostaCerta` TINYINT NOT NULL COMMENT 'tinyint=boolean',
  `descricaoR` VARCHAR(200) NOT NULL,
  `quantidadeAlter` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  PRIMARY KEY (`idResposta`),
  CONSTRAINT `fk_resposta_pergunta1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `green_go`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`questao_especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`questao_especie` (
  `idQuestaoEspecie` INT NOT NULL AUTO_INCREMENT,
  `idEspecie` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  PRIMARY KEY (`idQuestaoEspecie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `green_go`.`resp_usua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`resp_usua` (
  `idRespUsua` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  `acertou` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idRespUsua`),
  CONSTRAINT `fk_resp_usua_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `green_go`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resp_usua_resposta1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `green_go`.`resposta` (`idResposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida_zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida_zona` (
  `idPartidaZona` INT NOT NULL AUTO_INCREMENT, 
  `idZona` INT NOT NULL,
  `idPartida` INT NOT NULL,
  PRIMARY KEY (`idPartidaZona`),
  CONSTRAINT `fk_zona_has_partida_zona1`
    FOREIGN KEY (`idZona`)
    REFERENCES `green_go`.`zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_has_partida_partida1`
    FOREIGN KEY (`idPartida`)
    REFERENCES `green_go`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `green_go`.`partida_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `green_go`.`partida_equipe` (
  `idPartidaEquipe` INT NOT NULL AUTO_INCREMENT,
  `idEquipe` INT NOT NULL,
  `idPartida` INT NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`idPartidaEquipe`),
  CONSTRAINT `fk_equipe_has_partida_equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `green_go`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_partida_partida1`
    FOREIGN KEY (`idPartida`)
    REFERENCES `green_go`.`partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
